language: node_js
node_js:
  - "node"
# automatically deploy to gh-pages after passing on master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
